version: '3.9'

services:
  nginx:
    build:
      context: .
    ports:
      - ${EXTERNAL_HTTP_PORT}:80
      - ${EXTERNAL_SSH_PORT}:22
    environment:
      SSH_AUTHORIZED_KEY: ${SSH_AUTHORIZED_KEY}
    stdin_open: true
    tty: true
